# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: docker:latest

services:
  - docker:18.09-dind

stages:
  - build

variables:
  DOCKER_HOST: tcp://localhost:2375
  DOCKER_DRIVER: overlay2
  #IMAGE_TAG: erichardson/py-eagle-mqtt:$CI_COMMIT_TAG
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

before_script:
  - docker version
  - docker info
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build:
  only:
    - tags
  stage: build
  script:
    - docker build -t $IMAGE_TAG -t $CI_COMMIT_TAG ./Docker/
    - docker push $IMAGE_TAG $CI_COMMIT_TAG

#build:
#  stage: build
#  script:
#    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
#    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
#  except:
#    - master
